### ISSUE TITLE
About Ajenti cannot login

### ISSUE THREAD

**Issue by sistemarjin** [ajenti/ajenti#1004]
Hi,

I clean installed Ajenti 2.1.17 on Ubuntu 16.10 by this link. http://docs.ajenti.org/en/latest/man/install.html

I can connected on network https://IP:8000 login page is coming.
I cannot login.
User Name and password is OK, page is refreshing but cannot login.
If enter wrong UserName or Pass it giving error "Authentication Failed"
How i can fix it?

Thx

**Comment by dewafer** [comment]
Same problem here.

I was using `-v` and `--autologin` arguments to skip the login.
Edit `/lib/systemd/system/ajenti.service` with root, change 
```
ExecStart=/usr/bin/python /usr/local/bin/ajenti-panel -d
```
to
```
ExecStart=/usr/bin/python /usr/local/bin/ajenti-panel -d -v --autologin
```
Then restart the ajenti service using `service ajenti restart`.
You don't have to login any more.

According to the log, I think the problem is caused by the `aj/auth.py` file on line 103.
The `OSAuthenticationProvider` class is authenticating user using
```
/bin/sh -c '/bin/us -c "/bin/echo SUCCESS" - username
```
and expecting a feedback like `input your password:` and then send your password to authenticate.
And then it'll check your authentication by expecting `SUCCESS` was successfully echoed back from stdout.

But unfortunately, the installation in Ubuntu install the Ajenti as a service, it runs as a root user and has all the privileges root has.

So whatever user you want `su` to, the system won't promote you for password, so the authenticate here will always get an `Error checking password: Timeout exceeded.` exception here.

**Comment by s0urcelab** [comment]
same issue on debian8.
seem like skipping login is the only way to get in the ajenti2 right now.

**Comment by alfredocdmiranda** [comment]
Digging a little further in this issue. I've found that the problem is that Timeout exceeded, however it is not because it is waiting for an input, but for some reason the user `nobody` (`uid 99`) really take much time to use `su`. Why? I don't know.

I have tested manually and I got the same result.

So, my solution was to modify the timeout in the file `auth.py` inside the `aj` module, `line 103`. I put 100 seconds, but you can test others.

**Comment by pLavrenov** [comment]
Login with:
root
[password_root_user]

**Comment by ghost** [comment]
Login With:-    System username and Pasword

It will Work
