### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by qiaoshengchuan** [ajenti/ajenti#1054]
14.05.2017 16:54  [worker  6058]          gate.py:110   ERROR    Error checking password: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7f29ac07ebd0>
command: /bin/sh
args: ['/bin/sh', '-c', u'/bin/su -c "/bin/echo SUCCESS" - root']
buffer (last 100 chars): ''
before (last 100 chars): 'SUCCESS\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 6071
child_fd: 17
closed: False
timeout: 5
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(".*:")

**Comment by ImreBoersma** [comment]
Any progress on this problem? I'm experiencing it myself right now..

**Comment by chromaticsequence** [comment]
Experiencing this as well

**Comment by kiarn** [comment]
Hello,

I cannot reproduce this problem. Can you please specify the context ? install method ? OS ? Versions ?

Arnaud

**Comment by litteratum** [comment]
Hi @kiarn , could you please look into this problem?

I confirm that this issue still exists even in the latest Ajenti version (2.1.40).
Here is how to reproduce it:
1. Create a new clean Debian10 virtual machine / Docker container
2. Install Ajenti using the automated script: "curl https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install.sh | sudo bash -s -"
3. Go to "http://127.0.0.1:8000", log in with the root user
4. Change "Max session time" to some small value for testing purposes, e.g. 5s.
5. Wait for a session to expire and immediately type root/<root_password> and press "Log in"

With all those steps you should get an "Authentication failed" error. In a browser console: "Authentication failed null".
Ajenti log is the same as was attached in this bug report by @qiaoshengchuan.

Other information that may help:
* I experience this issue only for the "root" user
* If I wait for ~10s after a session is expired (and I am redirected back to "http://127.0.0.1:8000/view/login/normal"), I can log in without problems
* If a session is expired (and I am redirected back to "http://127.0.0.1:8000/view/login/normal"), I can go to "http://127.0.0.1:8000" and I'll be "attached" to the existing session without prompt for my credentials!

My understanding of the issue: for the "root" user, when a session is expired, for some reason it is not ended correctly and when you are redirected back to the login page, the session is still active. Pressing "Log in" updates the session lifetime. And you can't log in because the session is active.

Also, that time to wait I mentioned (~10s) seems to depend on "Max session time". I tried to set "Max session time" to 30s and I had to wait for ~30s after a session had expired.
So it really seems that when you are redirected back to the login page, the current session lifetime is updated and you should wait when it is really gets expired and removed.

Tested on Firefox/Chrome.

**Comment by kiarn** [comment]
Hello @ReturnedVoid 

Many thanks for your full description, it helps. I was not able to reproduce 5. but I will investigate further.
But I can confirm that the session still stay actived some seconds after the logout, and I will correct this.

**Comment by kiarn** [comment]
Hello,

I made some fixs based on the description of @ReturnedVoid, and I didn't encounter the problem in my tests.
For the error thrown from pexpect, it would be interessant to give the output of the following command in a terminal ( as non root user ): 

```
/bin/sh -c '/bin/su -c "/bin/echo SUCCESS" - root'
```

**Comment by litteratum** [comment]
@kiarn Thank you for your effort.

I am not sure where exactly should I run your command. But in Docker (Deb10) it prints "SUCCESS" for non-root user.

Could you please give some tips on how can I build ajenti from sources? I could test your fixes.
Or maybe there is some other way of how can I test it?

I tried to build it with "make build" but there are a lot of missing dependencies issues I can't resolve. The last dependency issue I can't resolve is with missing "babel". I tried to install "babel" with "npm" but it would not work. Installing "babel-cli" also does not work.

**Comment by kiarn** [comment]
@ReturnedVoid 

Sorry for the late reply, I'm quite busy actually. 

> I am not sure where exactly should I run your command. But in Docker (Deb10) it prints "SUCCESS" for non-root user.

On the machine on which ajenti should be installed. I suspect pexpect not to receive the right answer ( EOF or other ) and it would be interesting to know what in order to add the support for this. But "SUCCESS" is the right answer.

> Could you please give some tips on how can I build ajenti from sources? I could test your fixes.
> Or maybe there is some other way of how can I test it?
> 
> I tried to build it with "make build" but there are a lot of missing dependencies issues I can't resolve. The last dependency issue I can't resolve is with missing "babel". I tried to install "babel" with "npm" but it would not work. Installing "babel-cli" also does not work.

It's quite complicated because you need all librairies to compile the javascript. So there's a new version of Ajenti published today ( thanks @Eugeny ! ). You can try and please let me know if you encounter some problem, I will try to solve it.

Arnaud

**Comment by litteratum** [comment]
@kiarn 

You should not say sorry, your replies are actually fast :)

I installed ajenti v.2.1.42 using the automated script and may confirm that the current issue is fixed.

But there is a new bug not related to the current issue: when I go to "Plugins", there is a warning "Ajenti core 2.1.40. An upgrade to true is available".
"Update everything fails". I suspect commit https://github.com/ajenti/ajenti/commit/94031a56bf3b3a24619e2d6f19d701e104c3ca2c.

So the current issue may be closed, but the reported problem should be investigated.

**Comment by kiarn** [comment]
Thanks for your test and your feedback, I will close this.
There is already an issue for the upgrade problem : https://github.com/ajenti/ajenti/issues/1346
I will show at the mentioned commit, thanks for pointing it out :)
