### ISSUE TITLE
Login problem 

### ISSUE THREAD

**Issue by a937983423** [ajenti/ajenti#1350]
Why use root password to log in, it is restricted to many hosts. For security, root login and password login are prohibited, so what is the login panel?

**Comment by kiarn** [comment]
Hello,

I think you are speaking of 2 separate things :
- Ajenti need super user privileges on the server side in order to have access to all services to configure. Without this is Ajenti useless. If you don't have super user access on your server, it will be difficult to install Ajenti : is that your problem ?
- by default, the pam authenticator is enable in `/etc/ajenti/config.yml` (`provider:os`) which permit the root user to log in on the front panel. It's also possible to log in with user in the sudo group in order to use Ajenti. Disabling root login may be an option, but I must look at it first.

Arnaud

**Comment by a937983423** [comment]
For security, SSH has forbidden root to log in directly. You must log in to the general account in Su first, and then log in with all passwords. SSH is closed for security. How do you use it in this case

**Comment by a937983423** [comment]
Password login has been disabled. You must have the key to RSA

**Comment by kiarn** [comment]
You don't need SSH to use Ajenti, and you don't need to use the root account to log in in Ajenti panel.
You can log in with your username, and if this user ahs sudo permissions, then you can elevate in the panel ( click on the user menu to elevate ).

**Comment by cloudwindy** [comment]
I have a solution for this: #1357.
