### ISSUE TITLE
Ajenti installation on GCP DEBIAN 10 BUSTER (Need sudo su - before installation?)

### ISSUE THREAD

**Issue by locksmith-unit-orlando-fl** [ajenti/ajenti#1351]
Hello everybody :)
I noticed in the docs that don't specify if need to log in root:
sudo su - before installation?

I ask that because GCP gets you into the VM, not the true root.

and 

I get this warning in the installation:
`WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv     `

so i got confused. :/
HELP?

**Comment by kiarn** [comment]
Hello @locksmithunit 

Does GCP means Google Cloud Platform ?
Ajenti must run as root, because the whole point of Ajenti is to access and manage ressources on the server, so it's necessary to have all permissions.

Concerning the warning you get, it's clearly better to use a virtual environment. I made an automatic script to install Ajenti in a virtual env, but didn't have the time to test it further.
So, **if you are only testing, and if there's no risk on your test server**, you can eventually try the virtual env script : 

```
curl https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install-venv.sh | sudo bash -s -
```

I have tested it quickly on many platform ( Ubuntu, Debian, CentOS ), and it seems to work, but I cannot guarantee it.

Arnaud
