### ISSUE TITLE
Hello, I have problem with connecting to {myip}:8000 or {myip}. After reinstalling ajenti: service failed to start

### ISSUE THREAD

**Issue by ImaZen88** [ajenti/ajenti#1393]
root@Ubuntu-2004-focal-64-minimal ~ # service ajenti stop; ajenti-panel -v
Traceback (most recent call last):
  File "/usr/local/bin/ajenti-panel", line 123, in <module>
    if not os.path.exists(config_path):
  File "/usr/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

What can I do about it?

**Comment by kiarn** [comment]
Hello @ImaZen88,

Did you run the install as root ? Did you see a problem during the installation ? It seems that the config file `/etc/ajenti/config.yml` is missing.

Arnaud

**Comment by Nabhan87** [comment]
we have the same fate, I installed it on my ubuntu focal ip, even if I access it, there is no response

(device arm64)

**Comment by kiarn** [comment]
Hello @Nabhan87 

My tests for arm64 was until today not sufficent, mainly because installing `gevent` on this platform can not be done the same way as for the default install. I already wrote some details here : https://github.com/ajenti/ajenti/issues/1325.
But the question remains the same : was there a problem during the install process ?

Arnaud

**Comment by huhtig** [comment]
Leave a comment
