### ISSUE TITLE
FSTAB plugin does not seem to be working /view/fstab was not found on this server

### ISSUE THREAD

**Issue by wayneburlingame** [ajenti/ajenti#1406]
Hello,

FSTAB plugin does not seem to be working.
After installing plugin, which it appears to install without errors.
When going to filesystem I then get an error:
The URL http:<Webserver IP><Port:8000> /view/fstab was not found on this server.

System is: Ubuntu 18.04 without much else installed.

I am working on one other error I am getting for System>Network Yaml file error /usr/local/lib/python3.6 and am trying to verify my yaml file is configured properly, or if it is a code issue on your end, not sure yet though.
![fstab](https://user-images.githubusercontent.com/20672370/185068856-429f1213-5899-4134-b63f-485ba54061e0.png)
![network-yaml](https://user-images.githubusercontent.com/20672370/185068861-5f7309a2-bbb6-4beb-8955-8e75603c4bb9.png)

**Comment by wayneburlingame** [comment]
Here is the yaml error popup...
![network-yaml](https://user-images.githubusercontent.com/20672370/185069200-5014d49f-cc18-4c8c-a708-8910906f5e5b.png)

**Comment by kiarn** [comment]
Hello @wayneburlingame 

I'm currently AFK, so I just make a short answer : 

1) it seems that the fstab plugin is not loaded, maybe you can check this starting manually `Ajenti` with `ajenti-panel --dev` ( after stopping the systemd service ).
2) The network error comes from my code, because the netplan file is not properly parsed, I know it already.

Arnaud
