### ISSUE TITLE
Ajenti 2 Web UI all.js on debian 10

### ISSUE THREAD

**Issue by digimbyte** [ajenti/ajenti#1442]
Fresh debian install with only root

commands for setup
```
apt install -y sudo
apt install -y curl
apt install -y zip
curl https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install.sh | sudo bash -s -
systemctl status ajenti.service
```
all success

login to web panel on port 8000
UI frozen with multiple errors from all.js
```js
caught TypeError: Cannot read properties of undefined (reading 'getString')
    at all.js:1819:29
    at all.js:719:45
    at Scope.$apply (all.vendor.js:18124:13)
    at tick (all.vendor.js:12918:36)
```
appears completely useless.

I saw an older thread about stray symbols being interpreted wrongly for all.js but that was marked as resolved.

**Comment by kiarn** [comment]
Hello @digimbyte,

Is your machine eventually behind a proxy ?
If yes, please configure the variables `trusted_` in the config file : https://docs.ajenti.org/en/latest/man/config.html#other-global-parameters

If not, I think I need more of some of these errors, because with this one, I'm not able to understand what's going on.

Arnaud
