### ISSUE TITLE
Can it be (mis)used to execute custom commands?

### ISSUE THREAD

**Issue by mailinglists35** [ajenti/ajenti#1475]
I'm researching ways to allow support team to perform basic tasks such a restarting a service or viewing command outputs.

Is this project able to do this? For example to define commands in a configuration file.
Obviously wanting to disable all other functions like not allowing to restart any other service than what is defined, not allow terminal cli, etc

Thanks

**Comment by kiarn** [comment]
Hi @mailinglists35 

You can achieve this kind of behaviour by [developping your own plugin](https://docs.ajenti.org/en/latest/dev/intro.html#dev-getting-started) and integrating it in Ajenti.
It's also possible to set different permissions for the users.

Regards

Arnaud

**Comment by mailinglists35** [comment]
Arnaud, at first look through the demo plugins it seems a bit complicated - I only know shell scripting. 

Could you show a starting point? I could then clone and multiply to all commands that I need. 

An example with running system command "/usr/bin/systemctl restart someservice" and printing it's output would be sufficiently exactly what I need.

**Comment by kiarn** [comment]
Hello @mailinglists35 

Sorry for the late reply, I did not see your answer !
There's some demo plugin with minimal examples here : https://github.com/ajenti/demo-plugins

I think it's a goog starting point for understanding how it is working. Just ask if you need help ! (i will follow your answers ;) )

Arnaud

**Comment by mailinglists35** [comment]
yes, about those demo plugins I was referring them as too difficult to start with for someone with only bash scripting skills

**Comment by kiarn** [comment]
Each plugin contains a frontend part (javascript) and a backend part (python). 
I will take an example with https://github.com/ajenti/demo-plugins/blob/master/demo_4_http/views.py, and say you want to write a new plugin named `myplugin`
You will need to copy the whole `demo_4_http` directory and replace each reference to `demo_4_http` into `myplugin` (e.g. https://github.com/ajenti/demo-plugins/blob/master/demo_4_http/plugin.yml).

But in order to achieve this, you will need `ajenti-dev-multitool` in order to build the javascript part (follow the readme https://github.com/ajenti/demo-plugins/tree/master ).

The backend part for your request could simply be:

```python
import time
import subprocess
from jadi import component

from aj.api.http import url, HttpPlugin

from aj.api.endpoint import endpoint, EndpointError, EndpointReturn


@component(HttpPlugin)
class Handler(HttpPlugin):
    def __init__(self, context):
        self.context = context

    @url(r'/api/myplugin/someservice/restart')
    @endpoint(api=True)
    def handle_api_calculate(self, http_context):
        try:
            subprocess.check_output(['systemctl', 'restart', 'someservice'])
            return "Success"
        except Exception as e:
            raise EndpointError(e)
   
```

For the frontend:
- write a function which call the new API endpoint in https://github.com/ajenti/demo-plugins/blob/master/demo_4_http/resources/js/controllers/index.controller.coffee, like:

```javascript
$scope.restart_my_service = () ->
        $http.get("/api/myplugin/someservice/restart").success (data) ->
            $scope.result = data
        .error (err) ->
            notify.error 'Restart failed', err.message
            $scope.result = null
```

- put a button in the html file https://github.com/ajenti/demo-plugins/blob/master/demo_4_http/resources/partial/index.html linked to this new javascript function:

```html
<a ng:click="restart_my_service()" class="btn btn-default">Restart my service</a>
```

I hope it helps.

Arnaud
