### ISSUE TITLE
ajenti-v-mail not working

### ISSUE THREAD

**Issue by Mashpy** [ajenti/ajenti#666]
four month ago i have installed ajenti-v-mail on amazon ec2. i could successfully fo forward my contact@example.com  to abc@gmail.com. Recenty something wrong. when anyone send mail to contact@example.com , ajenti-v-mail does not forward it.

how can i solve this problem? can u check your ajenti-v-mail is working or not?

Is there any alternate of ajenti-v-mail ?

**Comment by Mashpy** [comment]
still i am facing the problem.

**Comment by seanmcn** [comment]
Ajenti-v mail is working as expected for me, I think you need to provide some more info to get help with your problem, you can't just say "Ajenti isn't forwarding mail" and expect answers.

Some log files would be helpful, they are located in /var/log/ 
Maybe, mail.err, mail.log, log files in /var/log/ajenti folder. etc. 

Have you changed the DNS settings of your domain lately perhaps?

Your problem is likely either Exim or Courier (whichever you went with) , not the Ajenti-v-mail package

**Comment by Teepareep** [comment]
this should also go in ajenti-v issues if you still think it's an issue :) https://github.com/Eugeny/ajenti-v/issues
