### ISSUE TITLE
Blank screen upon login

### ISSUE THREAD

**Issue by westjgames** [ajenti/ajenti#668]
After installing on Ubuntu 14.10, I can login remotely (after disabling SSL, which never works out of the box), however, I am presented with a blank screen. There is the usual Ajenti header and Feedback bar, but that's it. Nothing is clickable. I waited ages, checked my nework developer tab (a few XHTTP and WebSocket requests at regular intervals, all seemed to get a response) but nothing has shown. I have used both Chrome and Internet Explorer.

Interestingly enough, the story is totally different on the local machine itself. Loggin in via it's IP Address, hostname or 127.0.0.1 resulted in expected results, and a totally usable interface. But I need remote control. What can I do to fix this?

**Comment by gimmebytes** [comment]
Have you checked your bind option in the ajenti config file under /etc/ajenti ? It should look like:

`"bind": {
        "host": "0.0.0.0",
        "port": 8000
    }`

You could also try to change the host to the public IP of the machine.

Additionally I strongly recommend that you enable SSL again when the machine is accessible from the web. Otherwise your ajenti password will be transferred in plain text over the air. 

When I installed ajenti on my developer box (ubuntu-12.04) everything worked like a charm. What was the problem with SSL tough?

**Comment by westjgames** [comment]
I have always found I had to disable SSL before I could access the webpage, otherwise I got an ERR_CONNECTION_RESET in my browser. After manually pointing it to a crt file in unencrypted mode, it worked fine.

As for the settings, those are correct.

**Comment by westjgames** [comment]
I have noticed one difference between one setup that worked for me and this one which doesn't.

My problem machine is running 14.10 whereas the other one is running 14.04.1.

Could this just be a bug with 14.10?

**Comment by triniwiz** [comment]
i had this problem and this worked for me 

easy_install -U gevent

it was metioned in

https://github.com/Eugeny/ajenti/issues/618

**Comment by Eugeny** [comment]
The fixed `gevent-socketio` package (compatible with the new `gevent` versions) is now available in the Ajenti repo. You should be able to just update it, or install manually from http://repo.ajenti.org/debian/pool/ubuntu/g/gevent-socketio/python-gevent-socketio_0.3.7.99-1_all.deb
