### ISSUE TITLE
Logs will not display on Debian 7.8 (Wheezy)

### ISSUE THREAD

**Issue by VA1DER** [ajenti/ajenti#710]
The default location for logs on Debian is /var/log.  This is set up in the logs plugin, but nothing is shown when the plugin is selected.

**Comment by Xefir** [comment]
Tested on wheezy and jessie and this works

![crystalyx 2015-04-22 15-58-12](https://cloud.githubusercontent.com/assets/961976/7276213/7ce6914c-e908-11e4-95a8-da80f7faf599.png)

Do you open a file (using the open button) ?
By default nothing is shown because you have to select the log file you want to see.

**Comment by VA1DER** [comment]
So sorry.  My mistake.  I mistakenly believed the page was to be populated with the files there and you selected that way.
