### ISSUE TITLE
Ubuntu 15.04

### ISSUE THREAD

**Issue by ghost** [ajenti/ajenti#732]
Hi there is it possible to install ajenti on Ubuntu 15.04 x64

**Comment by salihklc** [comment]
I tried and the installation was good but I couldn't connect on any port

**Comment by Xefir** [comment]
Do you follow this steps : http://support.ajenti.org/topic/349868-installing-on-ubuntu/ ? 

If yes, you certainly facing the recurring issue with gevent : https://github.com/ajenti/ajenti/issues/702

You have to execute this command to fix gevent : 

`sudo easy_install -U gevent`

Restart ajenti after that and you will be able to access it in https on 8000 port.

**Comment by salihklc** [comment]
I follow these steps ( Easiest one )
When I try to reach https://myhost.com:8000 nothing happen. I read the #702, and look up logs you are looking right (you are right) but I can't solve problem neither with them which codes below. Correct me if I'm wrong ( I know I'm wrong). Thanks :)

`sudo wget -O- https://raw.github.com/ajenti/ajenti/1.x/scripts/install-ubuntu.sh -U gevent | sudo sh`
`sudo wget -O- https://raw.github.com/ajenti/ajenti/1.x/scripts/install-ubuntu.sh | sudo sh  -U gevent`
`sudo wget -O- https://raw.github.com/ajenti/ajenti/1.x/scripts/install-ubuntu.sh -U gevent | sudo sh  -U gevent`
`sudo easy_install -U gevent`

Edit:
 I run  `sudo easy_install -U gevent` after install gevent still not work

**Comment by Xefir** [comment]
Do you restart the ajenti's service after running the easy_install command ?
(`sudo service ajenti restart`)

If so, can you attach the ajenti.log located at `/var/log/ajenti/ajenti.log` ?

Thank you :-)

**Comment by salihklc** [comment]
Here is log file [LINK](http://we.tl/FMBhl6tQbU)

**Comment by Xefir** [comment]
The log shows that you're still using the default gevent.

Have you restarted ajenti like I said earlier ?
Has the `sudo easy_install -U gevent` returned a success message ?
What do you have in this directory `/usr/local/lib/python2.7/dist-packages/`? (the `easy_install -U gevent`'s command install the new gevent here).

A little note, maybe it could help you, but you have to had the python-dev package installed in order to build gevent, maybe this package is missing (but as I remember, the python-dev is part of the default packages on Ubuntu).

**Comment by salihklc** [comment]
Yes I restart ajenti like you said.
After run `sudo easy_install -U gevent` output is [LINK](http://we.tl/pad3Chl349)
And I have `easy-install.pth` in ` /usr/local/lib/python2.7/dist-packages/`
And I install gevent from [THIS](http://stackoverflow.com/a/9990181/3186326) stack answer. I still can't catch the problem :(

**Comment by Xefir** [comment]
Thank you for your last logs.
The `sudo easy_install -U gevent` is unsuccessfull because you don't have the gcc compiler (and build tools) installed.

Please run this command : `sudo apt-get install build-essential`

After this, please relaunch the `sudo easy_install -U gevent`'s command

Restart ajenti and voilà ! :D

**Comment by salihklc** [comment]
Finally I install easy_install , but after restart ajenti (`sudo service ajenti restart`and `/etc/init.d/ajenti restart` ) still not able to shown. I believed in you @Xefir :(
