### ISSUE TITLE
Changed NS, after that 503 Service Unavaible!

### ISSUE THREAD

**Issue by PontusTideman** [ajenti/ajenti#875]
Hi!

Tried to find any solution before posting this, but today I´ve changed to DigitalOceans NS and all is working find beside Ajenti is now throwing up **503 Service Unavailable** on the panel.mydomain.tld.

Yes, I know it takes some time before all DNS are populated with the new information. But I can reach the site from home, but it ends up with a 503 Service Unavailable.

Any clues around this and how to solve it ASAP?

**Comment by Xefir** [comment]
Before all, try to set your hostname in your hosts file.
This way, you cut the DNS problem to be sure it's not this problem here.

Second thing to take in note : did you go on the right protocol according to your config (if ssl, do https, if not, do http) ? And is the port open ? Did you type it in the address bar ?

Maybe this can help you, i hope.

**Comment by PontusTideman** [comment]
Ended up that my registrar has put in bad DNSSEC for one of my domains...

So close this one!

**Comment by Xefir** [comment]
I'm not a contributor, just a guy who help. I can't, so, can you please close it ? Thanks :)
