### ISSUE TITLE
Ubuntu 16.04 unmet install dependencies

### ISSUE THREAD

**Issue by ghost** [ajenti/ajenti#903]
I'm trying to install ajenti on 16.04 server. I started with a fresh install from snapshot as of March 31 and followed the instructions [for installing on Ubuntu](http://support.ajenti.org/topics/1121-installing-on-ubuntu/).. However, it fails to install, complaining of python dependencies.

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ajenti : Depends: python-support (>= 0.90.0) but it is not installable
          Depends: python-reconfigure (>= 0.1.46) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by gragio** [comment]
Download and install this http://launchpadlibrarian.net/109052632/python-support_1.0.15_all.deb
Run sudo apt-get install ajenti

**Comment by ghost** [comment]
After doing a bit of searching, it seems this isn't going to be a viable longterm solution as Ubuntu 16.04 [removes `python-support`](https://wiki.ubuntu.com/Python).

Indeed, that `deb` file is not compatible with Ubuntu 16.04, since its dependencies don't account for Ubuntu's move away from python2 in favor of python3.

```
test@ajenti:~$ sudo dpkg --install python-support_1.0.15_all.deb 
Selecting previously unselected package python-support.
(Reading database ... 59801 files and directories currently installed.)
Preparing to unpack python-support_1.0.15_all.deb ...
Unpacking python-support (1.0.15) ...
dpkg: dependency problems prevent configuration of python-support:
 python-support depends on python (>= 2.5); however:
  Package python is not installed.
 python-support depends on python-minimal; however:
  Package python-minimal is not installed.

dpkg: error processing package python-support (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 python-support
```

```
test@ajenti:~$ dpkg -l python-minimal
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                             Version               Architecture          Description
+++-================================-=====================-=====================-=====================================================================
un  python-minimal                   <none>                <none>                (no description available)
```

```
test@ajenti:~$ dpkg -l python3-minimal
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                             Version               Architecture          Description
+++-================================-=====================-=====================-=====================================================================
ii  python3-minimal                  3.5.1-3               amd64                 minimal subset of the Python language (default python3 version)
```

```
test@ajenti:~$ dpkg -l python
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                             Version               Architecture          Description
+++-================================-=====================-=====================-=====================================================================
un  python                           <none>                <none>                (no description available)
```

```
test@ajenti:~$ dpkg -l python3
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                             Version               Architecture          Description
+++-================================-=====================-=====================-=====================================================================
ii  python3                          3.5.1-3               amd64                 interactive high-level object-oriented language (default python3 vers
```

**Comment by ghost** [comment]
Looking at the contents of the `python-support` package, and searching the ajenti codebase (both of which I'm 100% unfamiliar with, just trying to evaluate ajenti to see if it's something I want to use on my new 16.04 server), I can't tell what ajenti is actually using from this package.

**Comment by Jonathan-Rosewood** [comment]
Greetings.
Succeeded solve the problem?

**Comment by ghost** [comment]
I will try again with the final 16.04 server release, but I may not have an
opportunity for a month or two.

**Comment by Jonathan-Rosewood** [comment]
I need to set up a new server and really want to make it under the control of 16.04, but ... but ... but ...
We can only wait

**Comment by AyoubTorabi** [comment]
`E: Unable to locate package ajenti`:((((

**Comment by justnice980** [comment]
Errors on Ubuntu Server 16.04 LTS final on install. 

empire@atlas:~$ sudo apt-get update && sudo apt-get install ajenti
Get:1 http://repo.ajenti.org/ng/debian main InRelease [11.6 kB]
Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease  
Hit:3 http://us.archive.ubuntu.com/ubuntu xenial InRelease  
Hit:4 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease
Fetched 11.6 kB in 0s (20.2 kB/s)  
Reading package lists... Done
W: http://repo.ajenti.org/ng/debian/dists/main/InRelease: Signature by key 425E018E23944B4B42814EE0BDC3FBAA53029759 uses weak digest algorithm (SHA1)
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ajenti : Depends: python-support (>= 0.90.0) but it is not installable
          Depends: python-reconfigure (>= 0.1.46) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by mechano** [comment]
I've put solution to the problem in the Ajenti installation page:

[http://support.ajenti.org/topics/1121-installing-on-ubuntu/](http://support.ajenti.org/topics/1121-installing-on-ubuntu/)

After some try I've been able to install and made to work Ajenti on Ubuntu 16.04.

First downloaded and installed this:

```
wget http://launchpadlibrarian.net/109052632/python-support_1.0.15_all.deb
sudo dpkg -i python-support_1.0.15_all.deb
```

Now ajenti installs without errors: 

`sudo apt-get install ajenti`

Ajenti starts and you can login, but there's only an empty page, so next steps are needed.

Edit those files:

```
sudo vi /usr/lib/python2.7/dist-packages/socketio/handler.py
sudo vi /usr/lib/python2.7/dist-packages/socketio/transports.py
```

find this line in both files:

`("Access-Control-Max-Age", 3600),`

add double quotes:

`("Access-Control-Max-Age", "3600"),`

restart Ajenti:

`sudo service ajenti restart`

login again to the panel.

**Comment by AyoubTorabi** [comment]
In the new version
My server has a problem with port 25.
And I have to close port 25.

"The server might be infected with malware that is being used to send spam, so please check for this as well. If you don't plan on sending emails, then please consider blocking port 25 using a software firewall."

**Comment by kingonoverall** [comment]
Same problem hier on Ubuntu 16.04
If you want just to try and see the basic Ajenti use:

`curl https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install.sh > install.sh && sudo bash install.sh`

and login with your normal account at the login page
There will be a problem with the user elevation rights. Normal user -> sudo user

**Comment by dbiers** [comment]
Confirmed that changes from @mechano resolved issue on a Ubuntu 14.04 LTS server with Ajenti installed that was upgraded to Ubuntu 16.04 LTS.

Additional steps needed to be taken in regards to PHP-FPM for the particular configuration I was working with but I was able to get this running as `php5-fpm`/`php-fpm` is now `php7.0-fpm`.

Thanks for the quick fix @mechano!

**Comment by janxb** [comment]
But please have in mind, that the fix mentioned above is just a dirty workaround and should not be the permanent solution for this problem.. ;)

**Comment by ender-null** [comment]
it's yet any workaround for php-fpm? @dbiers

**Comment by FixMiller** [comment]
@mechano 
tried your solution, but i get this:
Unpacking python-support (1.0.15) over (1.0.15) ...
dpkg: dependency problems prevent configuration of python-support:
 python-support depends on python (>= 2.5); however:
  Package python is not installed.
 python-support depends on python-minimal; however:
  Package python-minimal is not installed.

dpkg: error processing package python-support (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 python-support

Ubuntu Xenial 16.04, updated from Ubuntu 15.10

Did you have python 2.7 installed ?

**Comment by RJPalombo** [comment]
+1 for php-fpm - anyone have any ideas how to get the web hosting plugin to use php 7?

**Comment by Ardakilic** [comment]
I'm using Ajenti with PHP7 just fine (there's a general issue for unset configuration parameter), you need to set FPM match parameter manually. Check here:

https://github.com/Eugeny/ajenti-v/pull/213#issuecomment-218722433

@RJPalombo I wonder if this is your problem though.

**Comment by RJPalombo** [comment]
@Ardakilic , that worked! Thanks!

**Comment by c0fe** [comment]
dh_python2 appears to have replaced python-support. python-support has been removed from Debian and from Ubuntu. Has this issue been resolved yet for Ajenti?

**Comment by georg90** [comment]
I get the following error when starting ajenti with @mechano 's instructions:

<img width="396" alt="error" src="https://cloud.githubusercontent.com/assets/6489464/16173063/3e9a97d6-35c8-11e6-9f1f-9c5e46ed9db3.png">

I guess it's simply better to leave this until there is official python 3.5 support?

**Comment by spencerthayer** [comment]
I would REALLY like to to use Ajenti on Ubuntu 16.04.1 LTS without using @mechano's https://github.com/ajenti/ajenti/issues/903#issuecomment-215569332 hack. I'm wondering if @Eugeny is aware of this issue and if there is a legit fix in the near future?

**Comment by Eugeny** [comment]
@mechano @spencerthayer could you guys please try out this gevent-socketio package? http://repo.ajenti.org/debian/pool/ubuntu/g/gevent-socketio/python-gevent-socketio_0.3.7.99-1_all.deb

Unfortunately the gevent-socketio people don't seem to be releasing a fix anytime soon, so I have to try and build my own deb out of it

**Comment by Eugeny** [comment]
Any luck anyone?

**Comment by justnice980** [comment]
Nope.  I've given up on ajenti and switched back to webmin.

**Comment by georg90** [comment]
working fine on a fresh install :) thanks!

**Comment by Eugeny** [comment]
Great.

**Comment by MikelArnaiz** [comment]
I having issues too. I followed [a tutorial for Ubuntu 14.04](https://www.digitalocean.com/community/tutorials/how-to-install-the-ajenti-control-panel-and-ajenti-v-on-ubuntu-14-04) and it seems for 16.04 something changed.

@Eugeny  _commented on Aug 15_
> @mechano @spencerthayer could you guys please try out this gevent-socketio package? http://repo.ajenti.org/debian/pool/ubuntu/g/gevent-socketio/python-gevent-socketio_0.3.7.99-1_all.deb

What should I do with that .deb? 
Can I follow the [instructions of @mechano](#issuecomment-215569332) just replacing the URL and filename? e.g

```
wget http://repo.ajenti.org/debian/pool/ubuntu/g/gevent-socketio/python-gevent-socketio_0.3.7.99-1_all.deb
sudo dpkg -i python-gevent-socketio_0.3.7.99-1_all.deb
```

PS: Droplet in digitalocean with Ubuntu 16.04

**Comment by MikelArnaiz** [comment]
This worked for me:

1. `wget http://launchpadlibrarian.net/109052632/python-support_1.0.15_all.deb`
1. `sudo dpkg -i python-support_1.0.15_all.deb`
1. `sudo apt-get update && sudo apt-get install ajenti`
1. If error
    `sudo apt-get -f install`
1. Try to install again 
    `sudo apt-get update && sudo apt-get install ajenti`
1. If still fails try with the automatic script
    `wget -O- https://raw.github.com/ajenti/ajenti/1.x/scripts/install-ubuntu.sh | sudo sh`
1. Edit `handler.py`. (*Not needed for me*)
    * `sudo nano /usr/lib/python2.7/dist-packages/socketio/handler.py`
    * Find `("Access-Control-Max-Age", 3600),` 
    * Add double quotes so is is `("Access-Control-Max-Age", "3600"),`
1. Same with `transports.py`
    `sudo nano /usr/lib/python2.7/dist-packages/socketio/transports.py`
1. `sudo service ajenti restart`
1. Go to **https**://ip:8000. Important HTTPS.
1. Access
    Username: `root`
    Password: `admin`

**Comment by sathwiksunderreddy** [comment]
Hi I am getting this error on ubuntu server 16.04 when upgrading and update tried all the ways but still unable to get the dependencies any help.


admin@bizsoftonline:~$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libaudio2 libblas-common libblas3 liblinear3 liblua5.2-0 libmng2 libmysqlclient20
  libqt4-dbus libqt4-declarative libqt4-network libqt4-opengl libqt4-script libqt4-sql
  libqt4-sql-mysql libqt4-xml libqt4-xmlpatterns libqtcore4 libqtdbus4 libqtgui4 libqtwebkit4
  lua-lpeg mysql-common ndiff python-bs4 python-chardet python-html5lib python-lxml
  python-pkg-resources python-six qdbus qt-at-spi qtchooser qtcore4-l10n
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
10 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up python2.7 (2.7.12-1ubuntu0~16.04.1) ...
Traceback (most recent call last):
  File "/usr/lib/python2.7/py_compile.py", line 9, in <module>
    import os
  File "/usr/lib/python2.7/os.py", line 400, in <module>
    import UserDict
  File "/usr/lib/python2.7/UserDict.py", line 116, in <module>
    import _abcoll
  File "/usr/lib/python2.7/_abcoll.py", line 11, in <module>
    from abc import ABCMeta, abstractmethod
  File "/usr/lib/python2.7/abc.py", line 8, in <module>
    from _weakrefset import WeakSet
  File "/usr/lib/python2.7/_weakrefset.py", line 5, in <module>
    from _weakref import ref
ImportError: No module named _weakref
dpkg: error processing package python2.7 (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of python:
 python depends on python2.7 (>= 2.7.11-1~); however:
  Package python2.7 is not configured yet.

dpkg: error processing package python (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previou                                                                        s failure.
          dpkg: dependency problems prevent configuration of python-all:
 python-all depends on python (= 2.7.11-1); however:
  Package python is not configured yet.
 python-all depends on python2.7 (>= 2.7.2-3); however:
  Package python2.7 is not configured yet.

dpkg: error processing package python-all (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previou                                                                        s failure.
          dpkg: dependency problems prevent configuration of python-bs4:
 python-bs4 depends on python:any (<< 2.8); however:
  Package python is not configured yet.
 python-bs4 depends on python:any (>= 2.7.5-5~); however:
  Package python is not configured yet.

dpkg: error processing package python-bs4 (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
                                                              dpkg: dependency problems prevent                                                                         configuration of python-pkg-resources:
 python-pkg-resources depends on python:any (<< 2.8); however:
  Package python is not configured yet.
 python-pkg-resources depends on python:any (>= 2.7.5-5~); however:
  Package python is not configured yet.

dpkg: error processing package python-pkg-resources (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
                                                              dpkg: dependency problems prevent                                                                         configuration of python-chardet:
 python-chardet depends on python:any (<< 2.8); however:
  Package python is not configured yet.
 python-chardet depends on python:any (>= 2.7.5-5~); however:
  Package python is not configured yet.
 python-chardet depends on python-pkg-resources; however:
  Package python-pkg-resources is not configured yet.

dpkg: error processing package python-chardet (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
                                                              dpkg: dependency problems prevent                                                                         configuration of python-six:
 python-six depends on python:any (<< 2.8); however:
  Package python is not configured yet.
 python-six depends on python:any (>= 2.7.5-5~); however:
  Package python is not configured yet.

dpkg: error processing package python-six (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
                                                              dpkg: dependency problems prevent                                                                         configuration of python-html5lib:
 python-html5lib depends on python-six; however:
  Package python-six is not configured yet.
 python-html5lib depends on python:any (<< 2.8); however:
  Package python is not configured yet.
 python-html5lib depends on python:any (>= 2.7.5-5~); however:
  Package python is not configured yet.

dpkg: error processing package python-html5lib (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
                                                              dpkg: dependency problems prevent                                                                         configuration of python-lxml:
 python-lxml depends on python (>= 2.7); however:
  Package python is not configured yet.
 python-lxml depends on python (<< 2.8); however:
  Package python is not configured yet.

dpkg: error processing package python-lxml (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
                                                              dpkg: dependency problems prevent                                                                         configuration of ndiff:
 ndiff depends on python:any (<< 2.8); however:
  Package python is not configured yet.
 ndiff depends on python:any (>= 2.7.5-5~); however:
  Package python is not configured yet.
 ndiff depends on python-lxml; however:
  Package python-lxml is not configured yet.

dpkg: error processing package ndiff (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
                                                              Errors were encountered while proc                                                                        essing:
 python2.7
 python
 python-all
 python-bs4
 python-pkg-resources
 python-chardet
 python-six
 python-html5lib
 python-lxml
 ndiff
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by raysn0w** [comment]
Why was this closed? it's february 2017 and this problem is still not fixed.

**Comment by spencerthayer** [comment]
I agree with @raysn0w this does not appear to be a legitimate closure of the ticket.

**Comment by Eugeny** [comment]
@sathwiksunderreddy your python2.7 installation seems to be corrupted. You'll have to fix that first before trying anything else. I'd start with wiping and reinstalling all python related packages.

@spencerthayer it's hard to advise anything given that you didn't share your experience regarding the new .deb yet

**Comment by sathwiksunderreddy** [comment]
I tried it all the ways but there are few instances of python which I am unable to install at all the issue mainly is with python installation when I am trying to install python2.7 but none of the python packages are installed showing the same error......

I just changed the OS which resolved this issue

**Comment by c0fe** [comment]
Having dependency issues with Debian 8 install, fresh install of Debian and yet issues.

**Comment by petralian** [comment]
:( this project looked so good... now I have wiped my VPS over 10 times and still can't make it work on CentOS7, Ubuntu16, Debian8. Alas...

**Comment by c0fe** [comment]
@petralian it used to be good, I had it installed on any distros, Debian or CentOS with preexisting configurations with no problems. Now it seems that virtually all different configurations will cause Ajenti to freak out. And the developer apparently isn't interested in the slightest to fix.

Though this isn't surprising. Why use Nginx and not give the user a choice between Apache or Nginx? Screw the user, that's why.

**Comment by petralian** [comment]
@c0fe yeah that's kinda sad because I am on Virtualmin and have not found anything better yet... Totally not complaining about stability because Virtualmin is a rock steady webpanel but can get a bit heavy. I really hope ajenti can get better installation documentation and more support on different systems. I am very surprised it does not run on Debian 8 honestly. I reset my vps like 5 times to different distro's but in the end I had to give up. Too bad because ajenti looks amazing in both design and functionality. My guess is that the dev has no time left to upgrade it all and is working on ajenti 2 instead.

**Comment by c0fe** [comment]
@petralian if only ajenti 2 was anything usable, unfortunately it doesn't install on Debian/Ubuntu neither.

**Comment by c0fe** [comment]
@petralian take a look at https://runcloud.io/ maybe that might suit your needs

**Comment by ghost** [comment]
What could be the issue of this error? I could not install php5.6-dev
 
` sudo apt-get install  php5.6-dev 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php5.6-dev : Depends: shtool but it is not installable
              Recommends: dh-php but it is not going to be installed
              Recommends: pkg-php-tools but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`

**Comment by ghost** [comment]
Another error in adding to repository for php5.6
`sudo add-apt-repository ppa:ondrej/php5-5.6

Cannot add PPA: 'ppa:~ondrej/ubuntu/php5-5.6'.
The user named '~ondrej' has no PPA named 'ubuntu/php5-5.6'
Please choose from the following available PPAs:
 * 'apache2':  PPA for Apache 2.x
 * 'apache2-qa':  PPA for Apache2 (QA builds; experimental)
 * 'autotools':  PPA for autotools (not-supported; build-dependency; experimental)
 * 'bind9':  PPA for BIND 9
 * 'cmake':  PPA for CMake (not-supported, experimental)
 * 'common':  Common PPA packages
 * 'courier':  PPA for Courier MTA
 * 'cyrus-imapd':  PPA for Cyrus IMAP
 * 'debhelper':  PPA for Debhelper (and friends)
 * 'golang':  PPA for Go (experimental, build-dependency)
 * 'llvm':  PPA for LLVM
 * 'mariadb-10.0':  PPA for MariaDB 10.0 (don't use, broken)
 * 'mysql-5.5':  PPA for MySQL 5.5 (don't use, broken)
 * 'mysql-5.6':  PPA for MySQL 5.6 (don't use, broken)
 * 'mysql-5.7':  PPA for MySQL 5.7 (don't use, broken)
 * 'nginx':  PPA for NGINX with HTTP/2 on Ubuntu 14.04 LTS and higher
 * 'nginx-mainline':  PPA for NGINX Mainline with HTTP/2 on Ubuntu 14.04 LTS and higher
 * 'pelican':  PPA for Pelican
 * 'php':  ***** The main PPA for PHP (5.6, 7.0, 7.1) with many PECL extensions *****
 * 'php-qa':  PPA for PHP (QA builds; experimental)
 * 'php-zts':  PPA for PHP ZTS (experimental, unsupported)
 * 'php5-compat':  PPA with dummy compatibility php5* packages
 * 'pkg-dpkg':  dpkg and friends (very experimental)
 * 'pkg-gearman':  PPA for Gearman
 * 'pkg-nlnetlabs':  NLNetLabs Backported Packages
 * 'sandbox':  Sandbox for preparation of various packages (DON'T USE)
 * 'seafile':  PPA for Seafile
 * 'unbound':  PPA for Unbound (mainly a build-dep)
 * 'zonemaster':  PPA for Zonemaster
`

**Comment by c0fe** [comment]
@gyanendro the project is dead

**Comment by janxb** [comment]
@c0fe It might got no updates in the last months, but we are using it on our new system. You can manually use php7.1-fpm and it is still just working fine for us.

**Comment by ubuntume** [comment]
I just put down ajenti as well. I installed ajenti fine, but ajenti v shows no tabs for anything. Root login fails and requires editing to .yml file. I installed on a dedicated machine and nothing but dead ends. I like the design and the advertised product but the actual product isn't something I'd want to keep diving at with no stable starting ground.

**Comment by BCW52** [comment]
Follow this 
1. wget https://launchpad.net/ubuntu/+source/pillow/4.1.1-3build2/+build/13243580/+files/python-imaging_4.1.1-3build2_all.deb
2. sudo apt install python-olefile python-pil
3. sudo dpkg -i python-imaging_4.1.1-3build2_all.deb
Hope it will work who is facing this python imaging problem
