### ISSUE TITLE
issue browsing ajenti over https with NGINX setup

### ISSUE THREAD

**Issue by raymak23** [ajenti/ajenti#920]
Hello,

I am new to ajenti. I have configured ajenti best to my knowledge from online resources and google search. I am using centos 7 and I used ajenti yum repo to get latest ajenti packages. 

So the issue I am experiencing with ajenti is that I am unable to browse the application over https. I configured site level https in nginx and in `proxy_pass` I am using upstream alias called `ajenti`. Here is my nginx config setup:

```
upstream ajenti  {
    server 127.0.0.1:8000;
}

server {
server_name domain_name;
client_max_body_size 20m;

listen 80;
listen [::]:80;
listen 443 ssl;

ssl_certificate /path/www/domain_name/ssl/cert_chain.crt;
ssl_certificate_key /path/www/sunbelt/ssl/domain.key;

if ($scheme = http) {
    return 301 https://$server_name$request_uri;
}

location / {
#include fastcgi_params;
#fastcgi_pass    unix:/var/run/php-fpm/php-fpm.sock;
    proxy_redirect off;
    proxy_set_header   X-Real-IP         $remote_addr;
    proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_set_header   Host              $http_host;
    proxy_set_header   X-NginX-Proxy     true;
    proxy_set_header   Connection        "";
    proxy_http_version 1.1;
    proxy_pass http://ajenti;
   # proxy_ssl_trusted_certificate /etc/ajenti/ajenti.pem;
   # proxy_ssl_verify   off;
}
```

}

Here is my ajenti config.json settings for SSL:
     `"ssl": {
         "enable": false, 
         "certificate_path": "/etc/ajenti/ajenti.pem"
     }`

Here is what I get when I browse the application after putting username and password:
![screen shot 2016-05-09 at 9 30 17 pm](https://cloud.githubusercontent.com/assets/10405119/15134053/091e2d48-162e-11e6-9603-ff286fe4681c.png)

In NGINX and config.json when I use https configuration such as `proxy_pass https://ajenti` and `"ssl":{"enable": true}`, I get 502 bad gateway error.

Any help is really appreciated. :)

**Comment by ljnozz** [comment]
Read this: https://wildlyinaccurate.com/solving-502-bad-gateway-with-nginx-php-fpm/

**Comment by syzygyinteractivemedia** [comment]
I'm having the same issue. The problem is not related to PHP as @ljnozz is referring to...

@raymak23 is trying to reverse proxy Ajenti controlpanel via Nginx. I'm having the same problem with latest updates of python packages. Occurred after an apt-get upgrade...

I will try to put more error logging information here:

My ajenti package version are:

`dpkg -l |grep "gevent\|ajenti"`

`ii  ajenti                                1.2.23.11                      all          Server administration web interface`
`ii  ajenti-v                              0.2.58                         all          Virtual hosting solution for Ajenti`
`ii  ajenti-v-mysql                        0.3.8                          all          MySQL support for Ajenti V`
`ii  ajenti-v-nginx                        0.1.46                         all          NGINX support for Ajenti V`
`ii  ajenti-v-nodejs                       0.2.0                          all          Node.JS support for Ajenti V`
`ii  ajenti-v-php-fpm                      0.1.22                         all          PHP support for Ajenti V (via PHP-FPM)`
`ii  ajenti-v-php7.0-fpm                   0.1.21                         all          PHP support for Ajenti V (via PHP-FPM / ppa:ondrej/php)`
`ii  ajenti-v-python-gunicorn              0.2.14                         all          Python support for Ajenti V (via gunicorn)`
`ii  ajenti-v-ruby-unicorn                 0.1.7                          all          Ruby support for Ajenti V (via Unicorn)`
`ii  python-gevent                         1.1.2-1+b1                     amd64        gevent is a coroutine-based Python networking library`
`ii  python-gevent-socketio                0.3.7.99-1                     all          SocketIO server based on the Gevent pywsgi server, a Python`
`ii  python-gevent-websocket               0.9.3-1                        all          websocket library for the gevent networking library`

Here is my ajenti.error.log (from nginx):

`2017/09/15 16:53:39 [crit] 19364#19364: *14028 SSL_do_handshake() failed (SSL: error:1417118C:SSL routines:tls_process_server_hello:version too low) while SSL handshaking to upstream, client: 14.30.148.162, server: ajenti.myhost.com, request: "GET / HTTP/2.0", upstream: "https://10.0.0.14:8000/", host: "ajenti.myhost.com"
2017/09/15 16:53:40 [crit] 19364#19364: *14028 SSL_do_handshake() failed (SSL: error:1417118C:SSL routines:tls_process_server_hello:version too low) while SSL handshaking to upstream, client: 14.30.148.162, server: ajenti.myhost.com, request: "GET /favicon.ico HTTP/2.0", upstream: "https://10.0.0.14:8000/favicon.ico", host: "ajenti.myhost.com", referrer: "https://ajenti.myhost.com/"`

and this is my ajenti log file: (/var/log/ajenti/ajenti.log)

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 522, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 153, in _close_when_done
    return handle(*args)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 129, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 663, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 263, in __init__
    raise x
SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:661)
<Greenlet at 0x7fe5f817ff50: _close_when_done(<socket at 0x7fe5f3fcb390 fileno=[Errno 9] Bad fil, ('10.0.0.14', 40186))> failed with SSLError`

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 522, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 153, in _close_when_done
    return handle(*args)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 129, in wrap_socket_and_handle
    ssl_socket = self.wrap_socket(client_socket, **self.ssl_args)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 663, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_sslgte279.py", line 263, in __init__
    raise x
SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:661)
<Greenlet at 0x7fe5f817ff50: _close_when_done(<socket at 0x7fe5f3fcb390 fileno=[Errno 9] Bad fil, ('10.0.0.14', 40206))> failed with SSLError`

So it looks like the version of SSL for a handshake between the build-in ajenti ssllib (python) and the nginx ssl is not correct. 

I'm using nginx version: nginx/1.13.5
