### ISSUE TITLE
Change password from CLI?

### ISSUE THREAD

**Issue by IAmJulianAcosta** [ajenti/ajenti#939]
I'm trying to change the password from the CLI modifying `/etc/ajenti/config.json`, but is stored in plaintext, and I want to know if is possible to implement something that triggers the hashing.

**Comment by IAmJulianAcosta** [comment]
I'm not sure if this is still a thing, probably can get closed

**Comment by kiarn** [comment]
Hi, it looks like your issue is related to Ajenti v1.

Ajenti v1 has reached its end of life and although we gladly accept fixes and PRs, there isn't any new development happening.

As a non-profit project, we don't have the manpower available to provide support for v1 related issues. Thank you for your understanding.
