### ISSUE TITLE
Usernames are case sensitive

### ISSUE THREAD

**Issue by kroese** [ajenti/ajenti#970]
I frequently have troubles logging in to Ajenti because I always forget that the usernames are case-sensitive.

Is there any technical reason for this, and if not, can logins be made case insensitive?

**Comment by Serverfrog** [comment]
Firstly i think it is because the username which is inputed is checked for case sensitive equals.

Secondly , and in my opinion, it would be a security concern to make them case insensitive!
Think about it, these usernames would all the same:
- admin
- Admin
- ADMIN
- AdMiN
- aDmIn

A bot which try out different usernames must the not now how to write the username, but only the username itself. That makes it much more less an effort to brute force the account! The longer the username, the more is the difference between a case sensitive bruteforce and a case insensitive one.

PS: why not change the username or remember it correctly ;)

**Comment by noogen** [comment]
I agree with Serverfrog.  Though I believe the case sensitivity is driven, at it's core, by various system architecture.  Example: gh-page static page hosting is case sensitive, s3 is case sensitive, etc...    I generally follow the rule that, when in doubt, It's best to keep things in lower case.

It doesn't mean that implementing case insensitive is not possible.  You can always control it on the application side but it would be too much of a hassle.  It also doesn't solve the casing issue when somebody go into the 3rd party AUTH system and change the casing on you.  I guess I would vote this to be low priority as I rather see other things get fixed, unless people want to contribute and do a pull request.
