### ISSUE TITLE
Possible to install pagespeed and brotli?

### ISSUE THREAD

**Issue by venigo** [ajenti/ajenti#984]
Hi all,

I would like to ask if it is possible to install https://github.com/pagespeed/ngx_pagespeed and https://github.com/google/ngx_brotli on ajenti?

How can this be done? Is there a possible package available?

Looking forward to replies, thanks!

**Comment by noogen** [comment]
These are extensions to nginx.  I would think that you're better off just rebuilding nginx with these extensions.  Example: https://www.howtoforge.com/tutorial/how-to-install-nginx-and-google-pagespeed-on-ubuntu-16-04/

**Comment by venigo** [comment]
And how about Ajenti-V. Rebuild the python installer? Thanks!

**Comment by noogen** [comment]
I think all it is is generating nginx config.  If you have nginx already build/custom installed and it meet >= 1.4.0 (https://github.com/Eugeny/ajenti-v/blob/master/vh-nginx/package.desc) requirement, it would not install a new one.  

As for the config:  pagespeed can be at individual site/server config level and brotli is in the header: Accept-Encoding: 'brotli'

The biggest problem here is not being able to control the nginx.conf since it get blown away by Ajenti.  May have to play around to see if putting your config into /etc/nginx/conf.d/pagespeed.conf would work.

**Comment by noogen** [comment]
Answered my question above, you can put it in this folder: /etc/nginx.custom.global.d/pagespeed.conf 

Because it's reference on line 61 here: https://github.com/Eugeny/ajenti-v/blob/master/vh-nginx/nginx_templates.py

**Comment by w-biggs** [comment]
I'm wondering if it's possible to build nginx with pagespeed alongside ajenti-v as well. I'm not sure how to go about building nginx with pagespeed, when ajenti has already installed nginx for me. I'm kinda wanting to avoid downtime as well. Has anyone figured this out?

**Comment by venigo** [comment]
I am wondering this still to. I didnt manage to get it working out of of the box. As I dont want downtime. I there maybe a possiblity to create a plugin for ajenti v with tweaks and pagespeed extensions?
