### ISSUE TITLE
got bug report while deleting database for a website

### ISSUE THREAD

**Issue by saadamin** [ajenti/ajenti#989]
screen shot https://is.gd/DzQ0PR
can't delete the database , got this error https://is.gd/RSMEUe

Ajenti bug report
--------------------

Info | Value
----- | -----
Ajenti | 1.2.23.8
Platform | debian / ubuntu / Ubuntu 16.04.1 LTS
Architecture | x86_64 x86_64
Python | 2.7.12
Installation | 57962766
Debug | False
Catcher report | <!DOCTYPE html>

**Comment by noogen** [comment]
Did it delete?  Seem like a mysql server command line warning.  Maybe Ajenti delete function  should use some kind of driver instead of executing the mysql command directly into the terminal.  http://stackoverflow.com/questions/20751352/suppress-warning-messages-using-mysql-from-within-terminal-but-password-written

**Comment by saadamin** [comment]
I have reinstalled ajenti .
